import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import glob from "fast-glob";
import chokidar from "chokidar";
import type { FSWatcher } from "chokidar";
import type { Plugin } from "vite";

/**
 * Vite plugin that dynamically discovers mockup components and writes them to
 * a generated module under src/.generated. Uses fast-glob for initial
 * discovery and a dedicated chokidar watcher (with awaitWriteFinish) for
 * reliable file monitoring.
 *
 * Adapted from the component gallery plugin in pid2
 * (pkg/pid2/src/lib/vite/componentGalleryPlugin.ts).
 *
 * Generated module: "src/.generated/mockup-components.ts"
 * Exports: { modules: Record<string, () => Promise<Record<string, unknown>>> }
 *
 * When mockup files are added or removed, the generated module is rewritten.
 * Vite's normal file watching handles the update. If a relevant preview
 * request still returns 404 before the watcher settles, the dev server rescans
 * automatically. Individual file edits are handled by React Fast Refresh and
 * imported CSS HMR (no manual CSS invalidation needed).
 */

const MOCKUPS_DIR = "src/components/mockups";
const GENERATED_MODULE = "src/.generated/mockup-components.ts";

interface DiscoveredComponent {
  globKey: string;
  importPath: string;
}

export function mockupPreviewPlugin(): Plugin {
  let root = "";
  let currentSource = "";
  let watcher: FSWatcher | null = null;

  function getMockupsAbsDir(): string {
    return path.join(root, MOCKUPS_DIR);
  }

  function getGeneratedModuleAbsPath(): string {
    return path.join(root, GENERATED_MODULE);
  }

  function isMockupFile(absolutePath: string): boolean {
    const rel = path.relative(getMockupsAbsDir(), absolutePath);
    return (
      !rel.startsWith("..") && !path.isAbsolute(rel) && rel.endsWith(".tsx")
    );
  }

  function isPreviewTarget(relativeToMockups: string): boolean {
    return relativeToMockups
      .split(path.sep)
      .every((segment) => !segment.startsWith("_"));
  }

  async function discoverComponents(): Promise<Array<DiscoveredComponent>> {
    const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, {
      cwd: root,
      ignore: ["**/_*/**", "**/_*.tsx"],
    });

    return files.map((f) => ({
      globKey: "./" + f.slice("src/".length),
      importPath: path.posix.relative("src/.generated", f),
    }));
  }

  // Strict allowlist for paths we will embed into generated source code.
  // Only the characters that legitimately appear in mockup component file
  // paths are accepted: alphanumerics, dot, dash, underscore, slash and
  // (for relative imports) the leading `./` or `../`. Any path containing
  // anything else — quotes, backslashes, parens, NUL, line terminators
  // (including U+2028 / U+2029, which JSON.stringify does NOT escape and
  // which terminate JS source lines) — is rejected outright instead of
  // being interpolated into the generated module. This closes CodeQL
  // alert #144 (improper code sanitization).
  const SAFE_PATH_RE = /^(?:\.{1,2}\/)?[A-Za-z0-9._\-/]+$/;

  function safeStringifyPath(value: string): string {
    if (!SAFE_PATH_RE.test(value)) {
      throw new Error(
        `mockupPreviewPlugin: refusing to embed unsafe path ${JSON.stringify(value)} ` +
          `into generated module (only [A-Za-z0-9._\\-/] and a leading ./ or ../ are allowed)`,
      );
    }
    // Belt-and-braces: escape U+2028/U+2029 in case the regex above is
    // ever loosened — JSON.stringify leaves these characters untouched
    // even though they are valid line terminators in JS source.
    return JSON.stringify(value)
      .replace(/\u2028/g, "\\u2028")
      .replace(/\u2029/g, "\\u2029");
  }

  function generateSource(components: Array<DiscoveredComponent>): string {
    const entries = components
      .map(
        (c) =>
          `  ${safeStringifyPath(c.globKey)}: () => import(${safeStringifyPath(c.importPath)})`,
      )
      .join(",\n");

    return [
      "// This file is auto-generated by mockupPreviewPlugin.ts.",
      "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
      "export const modules: ModuleMap = {",
      entries,
      "};",
      "",
    ].join("\n");
  }

  function shouldAutoRescan(pathname: string): boolean {
    return (
      pathname.includes("/components/mockups/") ||
      pathname.includes("/.generated/mockup-components")
    );
  }

  let refreshInFlight = false;
  let refreshQueued = false;

  async function refresh(): Promise<boolean> {
    if (refreshInFlight) {
      refreshQueued = true;
      return false;
    }

    refreshInFlight = true;
    let changed = false;
    try {
      const components = await discoverComponents();
      const newSource = generateSource(components);
      if (newSource !== currentSource) {
        currentSource = newSource;
        const generatedModuleAbsPath = getGeneratedModuleAbsPath();
        mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
        writeFileSync(generatedModuleAbsPath, currentSource);
        changed = true;
      }
    } finally {
      refreshInFlight = false;
    }

    if (refreshQueued) {
      refreshQueued = false;
      const followUp = await refresh();
      return changed || followUp;
    }

    return changed;
  }

  async function onFileAddedOrRemoved(): Promise<void> {
    await refresh();
  }

  return {
    name: "mockup-preview",
    enforce: "pre",

    configResolved(config) {
      root = config.root;
    },

    async buildStart() {
      await refresh();
    },

    async configureServer(viteServer) {
      await refresh();

      const mockupsAbsDir = getMockupsAbsDir();
      mkdirSync(mockupsAbsDir, { recursive: true });

      watcher = chokidar.watch(mockupsAbsDir, {
        ignoreInitial: true,
        awaitWriteFinish: {
          stabilityThreshold: 100,
          pollInterval: 50,
        },
      });

      watcher.on("add", (file) => {
        if (
          isMockupFile(file) &&
          isPreviewTarget(path.relative(mockupsAbsDir, file))
        ) {
          void onFileAddedOrRemoved();
        }
      });

      watcher.on("unlink", (file) => {
        if (isMockupFile(file)) {
          void onFileAddedOrRemoved();
        }
      });

      viteServer.middlewares.use((req, res, next) => {
        const requestUrl = new URL(req.url ?? "/", "http://127.0.0.1");
        const pathname = requestUrl.pathname;
        const originalEnd = res.end.bind(res);

        res.end = ((...args: Parameters<typeof originalEnd>) => {
          if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
            void refresh();
          }
          return originalEnd(...args);
        }) as typeof res.end;

        next();
      });
    },

    async closeWatcher() {
      if (watcher) {
        await watcher.close();
      }
    },
  };
}
