import { Capacitor, registerPlugin } from "@capacitor/core";

const LocalNotifications = registerPlugin<any>("LocalNotifications");

const RING_NOTIFICATION_ID = 919191;
const NATIVE_RING_REPEAT_MS = 4500;
const NATIVE_RING_TITLE_FALLBACK = "Incoming call";
const NATIVE_RING_BODY_FALLBACK = "Tap to answer";

/**
 * Bundled ringtone audio asset (Task #46). Generated by
 * `scripts/generate-ringtone.ts` and committed to the repo so the file
 * is owned/royalty-free. The web ringer prefers this file over the Web
 * Audio synth fallback because (a) it sounds musical instead of
 * robotic, and (b) on iOS Safari an `<audio>` element backed by a real
 * resource is correctly silenced by the hardware mute switch — matching
 * WhatsApp behaviour. The Capacitor LocalNotifications channel
 * references the same asset name (`notification.wav`).
 */
const RINGTONE_AUDIO_SRC = "/sounds/notification.wav";

type OscillatorContext = {
    audioContext: AudioContext;
    masterGain: GainNode;
    intervalId: number;
    timeoutIds: number[];
    cancelled: boolean;
};

type NativeRingerHandle = {
    cancelled: boolean;
    intervalId: number | null;
};

let activeOscillator: OscillatorContext | null = null;
let activeNativeHandle: NativeRingerHandle | null = null;
let activeAudioElement: HTMLAudioElement | null = null;

/**
 * Monotonically-incrementing token for the current "ringing" intent.
 * Each call to `startWebRingtone()` bumps this; `stopWebRingtone()`
 * also bumps it. Async callbacks (such as a rejected `play()` promise
 * from a stale `startFileRingtone` attempt) capture the token they
 * were started under and refuse to fall back to the synth ringer if
 * the live token has moved on. Without this, a slow `play()` rejection
 * arriving AFTER the user has answered or hung up would leak a "ghost"
 * synth ringtone.
 */
let webRingtoneToken = 0;

function makeAudioContext(): AudioContext | null {
    try {
        const Ctor = (window.AudioContext || (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext);
        if (!Ctor) return null;
        return new Ctor();
    } catch {
        return null;
    }
}

function playRingPattern(ctx: OscillatorContext): void {
    const { audioContext, masterGain } = ctx;
    if (ctx.cancelled) return;

    // Two-tone "ringing" pattern (1300Hz then 1100Hz, 0.4s each).
    const now = audioContext.currentTime;
    const tones: Array<{ freq: number; offset: number; duration: number }> = [
        { freq: 1300, offset: 0, duration: 0.4 },
        { freq: 1100, offset: 0.45, duration: 0.4 },
    ];

    for (const tone of tones) {
        try {
            const osc = audioContext.createOscillator();
            const gain = audioContext.createGain();
            osc.type = "sine";
            osc.frequency.setValueAtTime(tone.freq, now + tone.offset);
            gain.gain.setValueAtTime(0, now + tone.offset);
            gain.gain.linearRampToValueAtTime(0.65, now + tone.offset + 0.04);
            gain.gain.linearRampToValueAtTime(0, now + tone.offset + tone.duration);
            osc.connect(gain).connect(masterGain);
            osc.start(now + tone.offset);
            osc.stop(now + tone.offset + tone.duration + 0.05);
        } catch {
            // If oscillator scheduling fails we just skip this beat.
        }
    }
}

function stopSynthRingtone(): void {
    if (!activeOscillator) return;
    activeOscillator.cancelled = true;
    if (activeOscillator.intervalId) {
        window.clearInterval(activeOscillator.intervalId);
    }
    activeOscillator.timeoutIds.forEach((id) => window.clearTimeout(id));
    try {
        activeOscillator.masterGain.gain.cancelScheduledValues(activeOscillator.audioContext.currentTime);
        activeOscillator.masterGain.gain.setValueAtTime(0, activeOscillator.audioContext.currentTime);
    } catch {
        // Ignore — context may already be closed.
    }
    try {
        void activeOscillator.audioContext.close();
    } catch {
        // Ignore — already closed.
    }
    activeOscillator = null;
}

function startSynthRingtone(): void {
    if (activeOscillator) return;

    const audioContext = makeAudioContext();
    if (!audioContext) return;

    const masterGain = audioContext.createGain();
    masterGain.gain.value = 1.0;
    masterGain.connect(audioContext.destination);

    const ctx: OscillatorContext = {
        audioContext,
        masterGain,
        intervalId: 0,
        timeoutIds: [],
        cancelled: false,
    };

    if (audioContext.state === "suspended") {
        // Will resume on the next user gesture; the interval will retry.
        void audioContext.resume().catch(() => undefined);
    }

    playRingPattern(ctx);
    ctx.intervalId = window.setInterval(() => {
        if (ctx.cancelled) return;
        if (audioContext.state === "suspended") {
            void audioContext.resume().catch(() => undefined);
        }
        playRingPattern(ctx);
    }, 1300);

    activeOscillator = ctx;
}

/**
 * Try to play the bundled WAV ringtone in a loop. Returns the audio
 * element on success (loop scheduled), or `null` if the browser does
 * not expose `Audio` (e.g. SSR / non-DOM environment). If
 * `audio.play()` is rejected later — typically because the browser
 * blocks autoplay until a user gesture — we fall back to the synth
 * tones automatically so the call still rings, BUT only if the
 * ring-intent token captured at start time is still the live one
 * (otherwise the user has already answered/declined and we must not
 * leak a "ghost" synth ringtone).
 */
function startFileRingtone(intentToken: number): HTMLAudioElement | null {
    if (typeof window === "undefined" || typeof Audio === "undefined") return null;
    let audio: HTMLAudioElement;
    try {
        audio = new Audio(RINGTONE_AUDIO_SRC);
    } catch {
        return null;
    }
    audio.loop = true;
    audio.preload = "auto";
    audio.volume = 1.0;

    const playPromise = audio.play();
    if (playPromise && typeof playPromise.then === "function") {
        playPromise.catch(() => {
            // Always release this stale element first.
            try { audio.pause(); } catch { /* ignore */ }
            if (activeAudioElement === audio) {
                activeAudioElement = null;
            }
            // Only start the synth fallback if the user is STILL
            // expecting to hear a ring. If `stopWebRingtone()` (or a
            // subsequent restart) has bumped the token, this rejection
            // belongs to a stale start and must not produce sound.
            if (intentToken !== webRingtoneToken) return;
            startSynthRingtone();
        });
    }
    return audio;
}

function stopFileRingtone(): void {
    if (!activeAudioElement) return;
    try {
        activeAudioElement.pause();
        activeAudioElement.currentTime = 0;
    } catch {
        // Ignore — element may already be detached.
    }
    activeAudioElement = null;
}

function stopWebRingtone(): void {
    // Bump the intent token so any in-flight `play()` rejection
    // arriving after this call cannot start the synth fallback.
    webRingtoneToken += 1;
    stopFileRingtone();
    stopSynthRingtone();
}

function startWebRingtone(): void {
    if (activeAudioElement || activeOscillator) return;

    // Bump the intent token so the new attempt has its own identity.
    // Async callbacks from this attempt will compare against this value
    // and refuse to act if it has moved on.
    webRingtoneToken += 1;
    const intentToken = webRingtoneToken;

    // Prefer the bundled audio asset (musical, mute-switch-aware on
    // iOS). Synth fallback only runs if the file ringer fails to
    // initialise or its play() promise is rejected.
    const audio = startFileRingtone(intentToken);
    if (audio) {
        activeAudioElement = audio;
        return;
    }

    startSynthRingtone();
}

async function scheduleNativeRingNotification(
    handle: NativeRingerHandle,
    options: { title: string; body: string },
): Promise<void> {
    if (handle.cancelled) return;
    if (!Capacitor.isPluginAvailable("LocalNotifications")) return;

    try {
        await LocalNotifications.schedule({
            notifications: [
                {
                    id: RING_NOTIFICATION_ID,
                    title: options.title,
                    body: options.body,
                    sound: undefined,
                    smallIcon: "ic_notification",
                    iconColor: "#f5a524",
                    ongoing: true,
                    autoCancel: false,
                    extra: {
                        category: "incoming_call",
                    },
                    channelId: "vex_incoming_calls",
                    actionTypeId: "VEX_INCOMING_CALL",
                    schedule: { at: new Date(Date.now() + 50) },
                },
            ],
        });
    } catch {
        // Best-effort — keep ringing even if scheduling fails.
    }
}

async function ensureNativeChannel(): Promise<void> {
    if (!Capacitor.isPluginAvailable("LocalNotifications")) return;
    try {
        await LocalNotifications.createChannel?.({
            id: "vex_incoming_calls",
            name: "Incoming Calls",
            description: "Incoming voice and video calls",
            importance: 5,
            visibility: 1,
            sound: "notification.wav",
            vibration: true,
            lights: true,
        });
    } catch {
        // Channel may already exist or plugin may not support it.
    }
}

async function startNativeRingtone(options: { title: string; body: string }): Promise<void> {
    if (activeNativeHandle) return;
    if (!Capacitor.isNativePlatform()) return;

    await ensureNativeChannel();

    const handle: NativeRingerHandle = { cancelled: false, intervalId: null };
    activeNativeHandle = handle;

    await scheduleNativeRingNotification(handle, options);

    handle.intervalId = window.setInterval(() => {
        if (handle.cancelled) return;
        void scheduleNativeRingNotification(handle, options);
    }, NATIVE_RING_REPEAT_MS);
}

async function stopNativeRingtone(): Promise<void> {
    if (!activeNativeHandle) return;
    activeNativeHandle.cancelled = true;
    if (activeNativeHandle.intervalId) {
        window.clearInterval(activeNativeHandle.intervalId);
    }
    activeNativeHandle = null;

    if (!Capacitor.isPluginAvailable("LocalNotifications")) return;
    try {
        await LocalNotifications.cancel?.({ notifications: [{ id: RING_NOTIFICATION_ID }] });
    } catch {
        // Ignore — best-effort cancellation.
    }
}

export interface CallRingtoneOptions {
    title?: string;
    body?: string;
    /** When true, start the loud native local-notification ringer in addition to the web tone. */
    includeNativeNotification?: boolean;
}

/**
 * Start a continuous ringing experience for an incoming or outgoing call.
 * Safe to call repeatedly — duplicate starts are ignored. Always call
 * `stopCallRingtone` once the call resolves.
 */
export function startCallRingtone(options: CallRingtoneOptions = {}): void {
    startWebRingtone();

    const wantsNative = options.includeNativeNotification !== false;
    if (wantsNative && Capacitor.isNativePlatform()) {
        void startNativeRingtone({
            title: options.title || NATIVE_RING_TITLE_FALLBACK,
            body: options.body || NATIVE_RING_BODY_FALLBACK,
        });
    }
}

export async function stopCallRingtone(): Promise<void> {
    stopWebRingtone();
    await stopNativeRingtone();
}

export function isCallRingtoneActive(): boolean {
    return !!activeOscillator || !!activeNativeHandle || !!activeAudioElement;
}
