/**
 * Shared world currencies list — used by settings, p2p, and other pages.
 * Each entry has a code, display name, and optional symbol.
 */

export interface CurrencyEntry {
  code: string;
  name: string;
  symbol?: string;
}

export const WORLD_CURRENCIES: CurrencyEntry[] = [
  // Major fiat currencies
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "LAK", name: "Lao Kip", symbol: "₭" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
  // Middle East
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "ب.د" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.أ" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "SYP", name: "Syrian Pound", symbol: "ل.س" },
  { code: "YER", name: "Yemeni Rial", symbol: "ر.ي" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  // North Africa
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س" },
  // Europe
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "RSD", name: "Serbian Dinar", symbol: "din" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
  { code: "BAM", name: "Bosnia Mark", symbol: "KM" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  // Central Asia
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "сўм" },
  { code: "TMT", name: "Turkmen Manat", symbol: "m" },
  { code: "KGS", name: "Kyrgystani Som", symbol: "сом" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  // Africa
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "Rs" },
  { code: "XOF", name: "West African CFA", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA", symbol: "FCFA" },
  // Americas
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "VES", name: "Venezuelan Bolivar", symbol: "Bs" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "₡" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
  { code: "TTD", name: "Trinidad Dollar", symbol: "TT$" },
  { code: "BBD", name: "Barbados Dollar", symbol: "Bds$" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$" },
  // Oceania
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$" },
  { code: "PGK", name: "Papua New Guinea Kina", symbol: "K" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
  // Crypto
  { code: "BTC", name: "Bitcoin", symbol: "₿" },
  { code: "ETH", name: "Ethereum", symbol: "Ξ" },
  { code: "USDT", name: "Tether USDT", symbol: "₮" },
  { code: "USDC", name: "USD Coin", symbol: "USDC" },
  { code: "BNB", name: "Binance Coin", symbol: "BNB" },
  { code: "XRP", name: "Ripple", symbol: "XRP" },
  { code: "SOL", name: "Solana", symbol: "SOL" },
  { code: "DOGE", name: "Dogecoin", symbol: "Ð" },
  { code: "ADA", name: "Cardano", symbol: "₳" },
  { code: "TRX", name: "Tron", symbol: "TRX" },
  { code: "LTC", name: "Litecoin", symbol: "Ł" },
  { code: "DOT", name: "Polkadot", symbol: "DOT" },
  { code: "MATIC", name: "Polygon", symbol: "MATIC" },
  { code: "AVAX", name: "Avalanche", symbol: "AVAX" },
  { code: "LINK", name: "Chainlink", symbol: "LINK" },
  { code: "XLM", name: "Stellar", symbol: "XLM" },
  { code: "ATOM", name: "Cosmos", symbol: "ATOM" },
  { code: "VET", name: "VeChain", symbol: "VET" },
  { code: "FIL", name: "Filecoin", symbol: "FIL" },
  { code: "ICP", name: "Internet Computer", symbol: "ICP" },
  { code: "APT", name: "Aptos", symbol: "APT" },
  { code: "ARB", name: "Arbitrum", symbol: "ARB" },
  { code: "OP", name: "Optimism", symbol: "OP" },
];

/** WORLD_CURRENCIES with an "all" entry prepended (for P2P filters etc.) */
export const WORLD_CURRENCIES_WITH_ALL: CurrencyEntry[] = [
  { code: "all", name: "All Currencies" },
  ...WORLD_CURRENCIES,
];

/** Format a currency entry for display: "USD - US Dollar ($)" */
export function formatCurrencyLabel(c: CurrencyEntry): string {
  return c.symbol ? `${c.code} - ${c.name} (${c.symbol})` : `${c.code} - ${c.name}`;
}
