import { randomUUID } from 'node:crypto';
import { storage } from '../storage';
import { db } from '../db';
import { liveGameSessions, gameMoves } from '@shared/schema';
import { eq } from 'drizzle-orm';
import { getGameEngine } from '../game-engines';
import type { MoveData } from '../game-engines/types';
import { logger } from '../lib/logger';
import {
  getAdaptiveAiSessionConfig,
  isAdaptiveAiPlayer,
  recordAdaptiveGameResult,
  recordAdaptiveHumanMove,
  resolveCurrentPlayerFromState,
} from '../lib/adaptive-ai';
import type { AuthenticatedWebSocket } from './types';
import { rooms } from './types';
import { send, sendError } from './utils';
import { handleGameOver } from './game-over';
import { startTurnTimer, clearTurnTimer } from './timers-disconnect';
import { getErrorMessage } from './types';
import { processAdaptiveAiTurns } from './ai-turns';
import { appendGameEvent, finalizeGameEvent } from '../lib/game-events';
import { runReplayShadowValidation, runSessionReplayValidation } from '../lib/game-replay-shadow';
import { evaluateAndRecordSubmission, evaluateAndRecordInvalid } from '../lib/game-level1-anomaly';
import { gameLevel1AnomalyTotal, wsMoveTurnMismatchRejectedTotal } from '../lib/prometheus-metrics';
import { persistGameSessionSnapshotIfDue } from '../lib/game-session-snapshots';
import { sessionMoveInFlightLimiter } from './inflight-move-limiter';

const GAME_EVENT_LOG_ENABLED = process.env.GAME_EVENT_LOG_ENABLED !== 'false';
const GAME_MOVE_IDEMPOTENCY_STRICT = process.env.GAME_MOVE_IDEMPOTENCY_STRICT !== 'false';
const GAME_EVENT_APPEND_FAIL_CLOSED_CANONICAL = process.env.GAME_EVENT_APPEND_FAIL_CLOSED_CANONICAL !== 'false';
const GAME_REPLAY_SHADOW_ENABLED = process.env.GAME_REPLAY_SHADOW_ENABLED !== 'false';

interface HandleMakeMovePayload {
  move: MoveData;
  expectedTurn?: number;
  idempotencyKey?: string;
  correlationId?: string;
}

export async function handleMakeMove(ws: AuthenticatedWebSocket, payload: HandleMakeMovePayload) {
  if (!ws.userId || !ws.sessionId) {
    sendError(ws, 'Not in a game');
    return;
  }

  if (ws.isSpectator) {
    sendError(ws, 'Spectators cannot make moves');
    return;
  }

  const room = rooms.get(ws.sessionId);
  if (!room) {
    sendError(ws, 'Game room not found');
    return;
  }

  const engine = getGameEngine(room.gameType);
  if (!engine) {
    sendError(ws, 'Game engine not available');
    return;
  }

  const sessionId = ws.sessionId;
  const userId = ws.userId;
  const normalizedIdempotencyKey = typeof payload.idempotencyKey === 'string'
    ? payload.idempotencyKey.trim().slice(0, 128)
    : '';
  if (GAME_MOVE_IDEMPOTENCY_STRICT && !normalizedIdempotencyKey) {
    sendError(ws, 'Missing idempotency key for move submission', 'IDEMPOTENCY_KEY_REQUIRED');
    return;
  }

  const attemptId = randomUUID();

  // Security/observability: correlationId must be server-controlled to avoid client injection.
  // When idempotencyKey exists, correlationId is deterministic for logical operation tracing.
  // Otherwise, we fall back to attemptId (physical attempt) generated by the server.
  const correlationId = normalizedIdempotencyKey
    ? `live_game_move_corr:${sessionId}:${userId}:${normalizedIdempotencyKey}`.slice(0, 128)
    : attemptId;

  const eventId = normalizedIdempotencyKey || correlationId;
  const moveId = normalizedIdempotencyKey || eventId;
  const idempotencyReference = normalizedIdempotencyKey
    ? `live_game_move_idem:${sessionId}:${userId}:${normalizedIdempotencyKey}`
    : `live_game_move_evt:${sessionId}:${userId}:${eventId}`;

  // In-flight backpressure: prevent concurrent make_move execution for the same session.
  // This protects the server from load amplification when clients spam from multiple tabs.
  const inFlightKey = `live_game_ws:inflight_move:${sessionId}`;
  const inFlight = sessionMoveInFlightLimiter.tryAcquire(inFlightKey);
  if (!inFlight.allowed) {
    send(ws, {
      type: 'move_rejected',
      payload: {
        event: 'in_flight_backpressure',
        error: 'Move is being processed, retry soon',
        errorKey: 'game.inFlightBackpressure',
        code: 'in_flight_backpressure',
        requiresSync: true,
        retryAfterMs: inFlight.retryAfterMs ?? null,
        correlationId,
        attemptId,
        sessionId,
        userId,
        status: 'rejected',
      }
    });
    return;
  }

  let isCanonicalSession = false;
  let moveEventRecordId: string | undefined;
  let appendFailed = false;

  if (GAME_EVENT_LOG_ENABLED && (GAME_EVENT_APPEND_FAIL_CLOSED_CANONICAL || GAME_REPLAY_SHADOW_ENABLED)) {
    try {
      const [sessionModeRow] = await db
        .select({ stateMode: liveGameSessions.stateMode })
        .from(liveGameSessions)
        .where(eq(liveGameSessions.id, sessionId))
        .limit(1);

      isCanonicalSession = sessionModeRow?.stateMode === 'CANONICAL';
    } catch (modeError) {
      logger.warn(`[GameEvents] Failed reading state mode for session ${sessionId}: ${modeError instanceof Error ? modeError.message : String(modeError)}`);
    }
  }

  if (GAME_EVENT_LOG_ENABLED) {
    try {
      const eventResult = await appendGameEvent({
        eventId,
        idempotencyKey: idempotencyReference,
        sessionId,
        source: 'live_game_ws',
        eventType: 'move',
        actorId: userId,
        actorType: 'player',
        moveType: typeof payload.move?.type === 'string' ? payload.move.type : 'move',
        payload: {
          move: payload.move as unknown as Record<string, unknown>,
          // Evidence-critical: keep audit records self-contained.
          sessionId,
          userId,
          correlationId,
          attemptId,
          // For moves, orderingIndex is the caller-provided expectedTurn when
          // present; otherwise we still provide the field for forensic
          // consistency.
          orderingIndex: payload.expectedTurn ?? null,
          receivedExpectedTurn: payload.expectedTurn ?? null,
          expectedTurn: payload.expectedTurn ?? null,
        },
      });

      if (eventResult.duplicate && normalizedIdempotencyKey && GAME_MOVE_IDEMPOTENCY_STRICT) {
        // Idempotency retry path:
        // The logical move was already recorded/processed, so treat it as success
        // for tracing and re-sync the client state to cover dropped ACK / reconnect.
        const freshSession = await storage.getLiveGameSession(sessionId);
        const freshTurnNumber = freshSession?.turnNumber ?? 0;

        if (freshSession?.gameState) {
          const syncView = engine.getPlayerView(freshSession.gameState, userId);
          send(ws, {
            type: 'move_accepted',
            payload: {
              gameType: room.gameType,
              correlationId,
              attemptId,
              isRetry: true,
              turnNumber: freshTurnNumber,
            }
          });

          send(ws, {
            type: 'state_sync',
            payload: {
              gameType: room.gameType,
              view: syncView,
              turnNumber: freshTurnNumber,
              correlationId,
              attemptId,
              isRetry: true,
            }
          });
        } else {
          // Fallback: if we can't load session state, keep backward-compatible rejection.
          // CIS: rejected events must be self-contained forensic artifacts.
          wsMoveTurnMismatchRejectedTotal.inc({ reason: 'duplicate_event_no_state' });

          const duplicateAuditEventId = randomUUID();
          const duplicateIdempotencyKey = `live_game_duplicate_reject:${sessionId}:${userId}:${correlationId}`.slice(0, 128);

          let duplicateAuditRecordId: string | undefined;

          try {
            const eventResult = await appendGameEvent({
              eventId: duplicateAuditEventId,
              idempotencyKey: duplicateIdempotencyKey,
              sessionId,
              source: 'live_game_ws',
              eventType: 'duplicate_move_rejection',
              actorId: userId,
              actorType: 'player',
              moveType: typeof payload.move?.type === 'string' ? payload.move.type : 'move',
              payload: {
                event: 'duplicate_move',
                status: 'rejected',
                sessionId,
                userId,
                correlationId,
                attemptId,
                orderingIndex: payload.expectedTurn ?? null,
                receivedExpectedTurn: payload.expectedTurn ?? null,
                dbTurn: null,
              },
            });

            duplicateAuditRecordId = eventResult.recordId;
            await finalizeGameEvent(duplicateAuditRecordId, 'rejected', 'duplicate_event');
          } catch (e) {
            logger.warn(`[CIS Audit] Failed to append duplicate-move rejection audit for session=${sessionId}: ${e instanceof Error ? e.message : String(e)}`);
          }

          send(ws, {
            type: 'move_rejected',
            payload: {
              event: 'duplicate_move',
              error: 'Duplicate move request ignored',
              errorKey: 'game.duplicateMove',
              code: 'duplicate_event',
              requiresSync: true,
              correlationId,
              attemptId,
              sessionId,
              userId,
              orderingIndex: payload.expectedTurn ?? null,
              receivedExpectedTurn: payload.expectedTurn ?? null,
              status: 'rejected',
            }
          });
        }
        return;
      }

      moveEventRecordId = eventResult.recordId;
      if (!eventResult.duplicate && !moveEventRecordId) {
        appendFailed = true;
      }
    } catch (eventError) {
      appendFailed = true;
      logger.warn(`[GameEvents] Failed to append live game event for session ${sessionId}: ${eventError instanceof Error ? eventError.message : String(eventError)}`);
    }
  }

  if (appendFailed && isCanonicalSession && GAME_EVENT_APPEND_FAIL_CLOSED_CANONICAL) {
    send(ws, {
      type: 'move_rejected',
      payload: {
        error: 'Move was rejected because event logging is unavailable',
        errorKey: 'game.eventLogUnavailable',
        code: 'event_log_unavailable',
        requiresSync: true,
        correlationId,
      }
    });
    return;
  }

  // Level-1 anomaly detection (rule-based) — CIS Security Control (Abuse/Malicious activity)
  const submissionAnomaly = evaluateAndRecordSubmission({
    sessionId,
    userId,
    gameType: room.gameType,
    now: Date.now(),
  });

  if (submissionAnomaly.blocked) {
    for (const anomalyType of submissionAnomaly.anomalies) {
      gameLevel1AnomalyTotal.inc({ anomalyType, result: 'blocked' });
    }

    await finalizeGameEvent(
      moveEventRecordId,
      'rejected',
      `level1_submission:${submissionAnomaly.anomalies[0] || 'anomaly'}`.slice(0, 64),
    );

    send(ws, {
      type: 'move_rejected',
      payload: {
        error: 'Move rejected due to suspicious activity',
        errorKey: 'game.level1Anomaly',
        code: 'level1_anomaly',
        requiresSync: true,
        retryAfterMs: submissionAnomaly.blockMs,
        correlationId,
      }
    });
    return;
  }

  try {
    const result = await db.transaction(async (tx) => {
      const [lockedSession] = await tx
        .select()
        .from(liveGameSessions)
        .where(eq(liveGameSessions.id, sessionId))
        .for('update');

      if (!lockedSession) {
        throw new Error('SESSION_NOT_FOUND');
      }

      if (lockedSession.status !== 'in_progress') {
        throw new Error('SESSION_NOT_ACTIVE');
      }

      const sessionPlayers = [
        lockedSession.player1Id,
        lockedSession.player2Id,
        lockedSession.player3Id,
        lockedSession.player4Id,
      ].filter(Boolean) as string[];

      if (!sessionPlayers.includes(userId)) {
        throw new Error('UNAUTHORIZED_PLAYER');
      }

      const dbState = lockedSession.gameState || engine.createInitialState();
      const dbTurn = lockedSession.turnNumber || 0;

      if (payload.expectedTurn !== undefined && payload.expectedTurn !== dbTurn) {
        // Explicit out-of-order / expectedTurn mismatch logging (no state leakage).
        // orderingIndex == caller-provided expectedTurn.
        logger.warn('[WS][TurnMismatch] expectedTurn mismatch', {
          sessionId,
          userId,
          gameType: room.gameType,
          correlationId,
          attemptId,
          orderingIndex: payload.expectedTurn,
          receivedExpectedTurn: payload.expectedTurn,
          dbTurn,
        });

        const error = Object.assign(new Error('TURN_MISMATCH'), { dbState, dbTurn });
        throw error;
      }

      const validation = engine.validateMove(dbState, userId, payload.move);
      if (!validation.valid) {
        const error = Object.assign(new Error('INVALID_MOVE'), { validationError: validation.error, errorKey: validation.errorKey });
        throw error;
      }

      const applyResult = engine.applyMove(dbState, userId, payload.move);
      if (!applyResult.success) {
        const error = Object.assign(new Error('MOVE_APPLY_FAILED'), { applyError: applyResult.error });
        throw error;
      }

      const newTurnNumber = dbTurn + 1;

      await tx
        .update(liveGameSessions)
        .set({
          gameState: applyResult.newState,
          turnNumber: newTurnNumber
        })
        .where(eq(liveGameSessions.id, sessionId));

      // SECURITY: Strip unknown properties from move data before storage to prevent data stuffing
      const allowedMoveKeys = ['type', 'from', 'to', 'promotion', 'die', 'dieValues', 'position', 'tileId', 'side',
        'card', 'bid', 'suit', 'rank', 'action', 'target', 'source', 'destination', 'piece', 'selectedTile',
        'playedTile', 'drawFromBoneyard', 'pass', 'endSide', 'trump', 'declaration', 'team', 'points',
        'gameType', 'trumpSuit', 'tile', 'end'];
      const sanitizedMove: Record<string, unknown> = {};
      for (const key of allowedMoveKeys) {
        if (key in payload.move) sanitizedMove[key] = (payload.move as Record<string, unknown>)[key];
      }

      await tx.insert(gameMoves).values({
        sessionId: sessionId,
        moveId,
        playerId: userId,
        moveNumber: newTurnNumber,
        moveType: payload.move.type || 'move',
        moveData: JSON.stringify(sanitizedMove),
        previousState: dbState,
        newState: applyResult.newState,
        isValid: true
      });

      return {
        preState: dbState,
        newState: applyResult.newState,
        events: applyResult.events,
        turnNumber: newTurnNumber,
        playerFallback: {
          player1Id: lockedSession.player1Id,
          player2Id: lockedSession.player2Id,
          player3Id: lockedSession.player3Id,
          player4Id: lockedSession.player4Id,
        },
      };
    });

    room.gameState = result.newState;

    if (isCanonicalSession && GAME_REPLAY_SHADOW_ENABLED) {
      runReplayShadowValidation({
        scope: 'live',
        gameType: room.gameType,
        sessionId,
        userId,
        move: payload.move,
        preState: result.preState,
        committedState: result.newState,
        turnNumber: result.turnNumber,
      }, engine);
    }

    await recordAdaptiveHumanMove({
      sessionId,
      userId,
      gameType: room.gameType,
      move: payload.move,
      turnNumber: result.turnNumber,
    });

    logger.info(`[WS] Move committed: session=${sessionId}, turn=${result.turnNumber}, player=${userId}, correlationId=${correlationId}`);

    // CIS snapshots (forensics / crash recovery / replay baselines)
    // Persist best-effort on a cadence decided by `persistGameSessionSnapshotIfDue`.
    try {
      await persistGameSessionSnapshotIfDue({
        sessionId,
        turnNumber: result.turnNumber,
        stateJson: result.newState,
        correlationId,
      });
    } catch (e) {
      // Never fail the move commit on snapshot persistence.
      logger.warn(`[Snapshot] Failed to persist snapshot for session=${sessionId} turn=${result.turnNumber}: ${e instanceof Error ? e.message : String(e)}`);
    }

    // Explicit success ACK for tracing/debugging (only the move sender)
    send(ws, {
      type: 'move_accepted',
      payload: {
        gameType: room.gameType,
        correlationId,
        attemptId,
        turnNumber: result.turnNumber,
      }
    });

    for (const [playerId, playerWs] of room.players) {
      const playerView = engine.getPlayerView(result.newState, playerId);
      send(playerWs, {
        type: 'game_update',
        payload: {
          gameType: room.gameType,
          events: result.events,
          view: playerView,
          turnNumber: result.turnNumber,
          correlationId,
          attemptId,
        }
      });
    }

    const spectatorView = engine.getPlayerView(result.newState, 'spectator');
    for (const [, spectatorWs] of room.spectators) {
      send(spectatorWs, {
        type: 'game_update',
        payload: {
          gameType: room.gameType,
          events: result.events,
          view: spectatorView,
          turnNumber: result.turnNumber,
          correlationId,
          attemptId,
        }
      });
    }

    const gameStatus = engine.getGameStatus(result.newState);
    if (gameStatus.isOver) {
      clearTurnTimer(sessionId);
      await recordAdaptiveGameResult({
        sessionId,
        gameType: room.gameType,
        status: gameStatus,
        stateJson: result.newState,
      });

      // Snapshot + replay verification (CIS Forensics)
      // We now store per-move previousState/newState in game_moves, so we can:
      // - pick an initialState from the earliest move snapshot
      // - replay the move sequence through engine.validateMove/applyMove
      // - compare with the committed final state
      try {
        const committedState = result.newState;
        const moves = await storage.getGameMoves(sessionId);

        if (moves.length > 0) {
          const first = moves[0];
          const initialState = first.previousState || engine.createInitialState();

          const events = moves.map((m) => {
            const parsedMove = (() => {
              try {
                return JSON.parse(m.moveData) as unknown;
              } catch {
                return null;
              }
            })();

            return {
              actorId: m.playerId,
              payload: {
                move: parsedMove,
              },
            };
          });

          const replayResult = runSessionReplayValidation(
            {
              scope: 'live',
              gameType: room.gameType,
              initialState,
              events,
              committedState,
              sessionId,
              turnNumber: result.turnNumber,
            },
            engine,
          );

          // CIS evidence: always record replay verification result (pass/fail).
          const replayEventId = randomUUID();
          const replayCorrelationId = `live_game_session_replay:${sessionId}:${result.turnNumber}:${replayEventId}`.slice(0, 128);

          let recordId: string | undefined;

          try {
            const errCode = `replay_drift:${replayResult.reason}`.slice(0, 64);

            const eventResult = await appendGameEvent({
              eventId: replayEventId,
              idempotencyKey: `live_game_session_replay_idem:${sessionId}:${result.turnNumber}:${replayEventId}`.slice(0, 128),
              sessionId,
              source: 'live_game_ws',
              eventType: 'session_replay_verification',
              actorId: userId,
              actorType: 'system',
              moveType: 'replay',
              payload: {
                // CIS forensic: self-contained audit artifact
                correlationId: replayCorrelationId,
                attemptId: replayEventId,
                orderingIndex: result.turnNumber,
                sessionId,
                userId,

                drift: replayResult.drift,
                reason: replayResult.reason,
                expectedHash: replayResult.expectedHash ?? null,
                replayHash: replayResult.replayHash ?? null,
              },
            });

            recordId = eventResult.recordId;

            if (replayResult.drift) {
              await finalizeGameEvent(recordId, 'rejected', errCode);
            } else {
              await finalizeGameEvent(recordId, 'applied');
            }
          } catch (e) {
            logger.warn(`[ReplayVerify] Failed to append replay verification event for session=${sessionId}: ${e instanceof Error ? e.message : String(e)}`);
          }

          if (replayResult.drift) {
            logger.warn('[ReplayVerify] Drift detected', {
              sessionId,
              gameType: room.gameType,
              correlationId: replayCorrelationId,
              reason: replayResult.reason,
              expectedHash: replayResult.expectedHash,
              replayHash: replayResult.replayHash,
            });
          }
        }
      } catch (e) {
        logger.warn(`[ReplayVerify] Session replay verification failed for session=${sessionId}: ${e instanceof Error ? e.message : String(e)}`);
      }

      await handleGameOver(room, gameStatus);
    } else {
      // Start turn timer for the next player
      const aiConfig = await getAdaptiveAiSessionConfig(sessionId);
      const nextPlayer = resolveCurrentPlayerFromState(room.gameType, result.newState, result.playerFallback);

      if (isAdaptiveAiPlayer(aiConfig, nextPlayer)) {
        await processAdaptiveAiTurns(sessionId, room);
      } else if (nextPlayer) {
        startTurnTimer(sessionId, nextPlayer, room.turnTimeLimitMs);
      }
    }

    await finalizeGameEvent(moveEventRecordId, 'applied');
  } catch (error: unknown) {
    const errorMessage = getErrorMessage(error);

    // If the move was invalid, apply Level-1 invalid-move spam detection.
    let errorCodeFinal = errorMessage.slice(0, 64);
    if (errorMessage === 'INVALID_MOVE') {
      const invalidAnomaly = evaluateAndRecordInvalid({
        sessionId,
        userId,
        gameType: room.gameType,
        now: Date.now(),
      });

      if (invalidAnomaly.blocked) {
        for (const anomalyType of invalidAnomaly.anomalies) {
          gameLevel1AnomalyTotal.inc({ anomalyType, result: 'blocked' });
        }
        errorCodeFinal = `level1_invalid:${invalidAnomaly.anomalies[0] || 'anomaly'}`.slice(0, 64);
      }
    }

    await finalizeGameEvent(moveEventRecordId, 'rejected', errorCodeFinal);

    console.error('[WS] Move transaction failed:', error);

    const syncRoom = async () => {
      const freshSession = await storage.getLiveGameSession(sessionId);
      if (freshSession?.gameState) {
        room.gameState = freshSession.gameState;
        const syncView = engine.getPlayerView(freshSession.gameState, userId);
        send(ws, {
          type: 'state_sync',
          payload: {
            gameType: room.gameType,
            view: syncView,
            turnNumber: freshSession.turnNumber,
            correlationId,
          }
        });
      }
    };

    if (errorMessage === 'SESSION_NOT_FOUND') {
      sendError(ws, 'Session not found', 'SESSION_NOT_FOUND');
    } else if (errorMessage === 'SESSION_NOT_ACTIVE') {
      sendError(ws, 'Game is not active', 'SESSION_NOT_ACTIVE');
      await syncRoom();
    } else if (errorMessage === 'UNAUTHORIZED_PLAYER') {
      sendError(ws, 'Not authorized to play in this session', 'UNAUTHORIZED');
      await syncRoom();
    } else if (errorMessage === 'TURN_MISMATCH') {
      const receivedExpectedTurn = payload.expectedTurn ?? null;

      // Prometheus metric
      wsMoveTurnMismatchRejectedTotal.inc({ reason: 'turn_mismatch' });

      // CIS: audit-grade forensic, self-contained rejection + structured rejection
      const turnMismatchAuditEventId = randomUUID();
      const turnMismatchIdempotencyKey = `live_game_turn_mismatch:${sessionId}:${userId}:${turnMismatchAuditEventId}`.slice(0, 128);

      try {
        const dbTurn = (error as Error & { dbTurn?: unknown }).dbTurn ?? null;

        const eventResult = await appendGameEvent({
          eventId: turnMismatchAuditEventId,
          idempotencyKey: turnMismatchIdempotencyKey,
          sessionId,
          source: 'live_game_ws',
          eventType: 'turn_mismatch',
          actorId: userId,
          actorType: 'player',
          moveType: typeof payload.move?.type === 'string' ? payload.move.type : 'move',
          payload: {
            event: 'turn_mismatch',
            status: 'rejected',
            sessionId,
            userId,
            correlationId,
            attemptId,
            orderingIndex: receivedExpectedTurn,
            receivedExpectedTurn,
            dbTurn,
          },
        });

        await finalizeGameEvent(eventResult.recordId, 'rejected', 'turn_mismatch');
      } catch (e) {
        logger.warn(
          `[CIS Audit] Failed to append turn_mismatch audit for session=${sessionId}: ${e instanceof Error ? e.message : String(e)}`
        );
      }

      send(ws, {
        type: 'move_rejected',
        payload: {
          // Backward-compatible keys
          error: 'Game state has changed. Syncing...',
          errorKey: 'game.turnMismatch',
          requiresSync: true,
          correlationId,

          // CIS forensic extras
          event: 'turn_mismatch',
          status: 'rejected',
          attemptId,
          sessionId,
          userId,
          orderingIndex: receivedExpectedTurn,
          receivedExpectedTurn,
          dbTurn: (error as Error & { dbTurn?: unknown }).dbTurn ?? null,
          reason: 'turn_mismatch',
        }
      });
      await syncRoom();
    } else if (errorMessage === 'INVALID_MOVE') {
      const moveErr = error as Error & { validationError?: string; errorKey?: string };
      send(ws, {
        type: 'move_rejected',
        payload: { error: moveErr.validationError, errorKey: moveErr.errorKey, requiresSync: true, correlationId }
      });
    } else if (errorMessage === 'MOVE_APPLY_FAILED') {
      const applyErr = error as Error & { applyError?: string };
      send(ws, {
        type: 'move_rejected',
        payload: { error: applyErr.applyError, correlationId }
      });
    } else {
      sendError(ws, 'Failed to save move. Please try again.');
      await syncRoom();
    }
  }
}
