// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vex-home/Holographic.tsx": () => import("../components/mockups/vex-home/Holographic.tsx"),
  "./components/mockups/vex-home/LiveFeed.tsx": () => import("../components/mockups/vex-home/LiveFeed.tsx"),
  "./components/mockups/vex-home/Stadium.tsx": () => import("../components/mockups/vex-home/Stadium.tsx")
};
