/**
 * Strongly-typed Socket.IO event contracts shared between client and server.
 * Two namespaces:
 *  - /chat : lightweight realtime chat in challenge / DM rooms
 *  - /rtc  : WebRTC signaling for voice / video calls
 *
 * Auth: every Socket.IO connection re-uses the existing `vex_token` JWT cookie
 * (or Authorization Bearer header during the handshake). No new auth surface.
 */

/* ============================================================================
 *  Common
 * ========================================================================== */

export type CallType = "voice" | "video";

/** 3-tier WebRTC fallback the client orchestrator may settle on */
export type CallTier = "p2p" | "relay" | "text-only";

export interface IceServerConfig {
  urls: string | string[];
  username?: string;
  credential?: string;
}

export interface IceServersResponse {
  iceServers: IceServerConfig[];
  /** Seconds until the TURN credential expires; 0 if no TURN configured */
  ttlSeconds: number;
  /** Whether a TURN relay is actually available (false → only public STUN) */
  hasRelay: boolean;
}

/* ============================================================================
 *  /chat namespace
 * ========================================================================== */

export interface ChatJoinPayload {
  /** Logical room id; e.g. `challenge:<id>`, `dm:<userA>:<userB>` */
  roomId: string;
}

export interface ChatMessagePayload {
  roomId: string;
  /** Plain text, max 500 chars */
  text: string;
  /** Optional client-generated id for de-dup / ack */
  clientMsgId?: string;
}

export interface ChatBroadcast {
  roomId: string;
  fromUserId: string;
  fromUsername: string;
  text: string;
  ts: number;
  /** Echo of clientMsgId if provided */
  clientMsgId?: string;
}

export interface ChatErrorPayload {
  code: "auth" | "rate_limit" | "invalid" | "server" | "forbidden" | "spectator_readonly";
  message: string;
}

export interface ChatClientToServerEvents {
  "chat:join": (p: ChatJoinPayload, ack?: (ok: boolean) => void) => void;
  "chat:leave": (p: ChatJoinPayload) => void;
  "chat:send": (
    p: ChatMessagePayload,
    ack?: (res: { ok: boolean; error?: string }) => void,
  ) => void;
  "ping": (ack: (pong: { ts: number }) => void) => void;
}

export interface ChatServerToClientEvents {
  "chat:message": (msg: ChatBroadcast) => void;
  "chat:error": (err: ChatErrorPayload) => void;
  "chat:joined": (p: { roomId: string; members: number }) => void;
}

/* ============================================================================
 *  /rtc namespace — WebRTC signaling
 * ========================================================================== */

export interface RtcInvitePayload {
  /** Logical call session id (UUID generated by initiator) */
  sessionId: string;
  /** Recipient user id */
  toUserId: string;
  callType: CallType;
  /** Optional context (e.g. challengeId so the callee knows the source) */
  context?: { challengeId?: string };
}

export interface RtcAnswerPayload {
  sessionId: string;
  accept: boolean;
}

export interface RtcSdpPayload {
  sessionId: string;
  toUserId: string;
  sdp: RTCSessionDescriptionInit;
}

export interface RtcIcePayload {
  sessionId: string;
  toUserId: string;
  candidate: RTCIceCandidateInit;
}

export interface RtcEndPayload {
  sessionId: string;
  /** Optional reason ('hangup', 'failed', 'fallback', etc.) */
  reason?: string;
  /**
   * Optional explicit recipient user id. Required when ending a call BEFORE
   * the SDP exchange (i.e. cancelling while ringing) because the callee
   * hasn't joined the per-call room yet — the server uses this to deliver
   * `rtc:ended` directly to the recipient's user-room.
   */
  toUserId?: string;
}

export interface RtcTierPayload {
  sessionId: string;
  tier: CallTier;
}

export interface RtcClientToServerEvents {
  "rtc:invite": (
    p: RtcInvitePayload,
    ack?: (res: { ok: boolean; error?: string }) => void,
  ) => void;
  "rtc:answer": (p: RtcAnswerPayload) => void;
  "rtc:sdp": (p: RtcSdpPayload) => void;
  "rtc:ice": (p: RtcIcePayload) => void;
  "rtc:end": (p: RtcEndPayload) => void;
  "rtc:tier": (p: RtcTierPayload) => void;
  "ping": (ack: (pong: { ts: number }) => void) => void;
}

export interface RtcServerToClientEvents {
  "rtc:incoming": (p: RtcInvitePayload & { fromUserId: string; fromUsername: string }) => void;
  "rtc:answered": (p: RtcAnswerPayload & { fromUserId: string }) => void;
  "rtc:sdp": (p: { sessionId: string; fromUserId: string; sdp: RTCSessionDescriptionInit }) => void;
  "rtc:ice": (p: { sessionId: string; fromUserId: string; candidate: RTCIceCandidateInit }) => void;
  "rtc:ended": (p: RtcEndPayload & { fromUserId: string }) => void;
  "rtc:tier": (p: RtcTierPayload & { fromUserId: string }) => void;
  "rtc:error": (p: { code: string; message: string; sessionId?: string }) => void;
}

/* ============================================================================
 *  Path constants (must match on both ends)
 * ========================================================================== */

export const SOCKETIO_PATH = "/socket.io";
export const SOCKETIO_NS_CHAT = "/chat";
export const SOCKETIO_NS_RTC = "/rtc";
